approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmPreapprovedPackages:
  - "@educorvi/*"

npmRegistryServer: "https://registry.npmjs.org"
